version: "3"

services:
  server:
    build: ./server
    container_name: dotnet-server
    restart: always
    env_file:
      - .env.production
    networks:
      - app-network

  client:
    build: ./client
    container_name: svelte-client
    restart: always
    depends_on:
      - server
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    depends_on:
      - client
    ports:
      - "4080:80"
    networks:
      - app-network
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
